-- Preset Indonesian Red Flag Game cards (~60 cards)
-- Red flags
insert into public.cards (text, type, category) values
  ('Masih temenan sama mantan', 'red', 'kebiasaan'),
  ('Reply WA 3 hari kemudian', 'red', 'kebiasaan'),
  ('Ngomongin mantan terus', 'red', 'kepribadian'),
  ('Gak pernah bayar duluan', 'red', 'gaya_hidup'),
  ('Selalu datang terlambat', 'red', 'kebiasaan'),
  ('Nyombongin diri terus', 'red', 'kepribadian'),
  ('Gak pernah minta maaf duluan', 'red', 'kepribadian'),
  ('Selalu drama di medsos', 'red', 'kebiasaan'),
  ('Gak bisa hidup tanpa validasi orang', 'red', 'kepribadian'),
  ('Bohong soal hal kecil', 'red', 'kepribadian'),
  ('Posesif dan cemburuan berlebihan', 'red', 'kepribadian'),
  ('Gak pernah dengerin orang lain', 'red', 'kepribadian'),
  ('Selalu salahkan orang lain', 'red', 'kepribadian'),
  ('Ghosting tiba-tiba', 'red', 'kebiasaan'),
  ('Gak mau kompromi sama sekali', 'red', 'kepribadian'),
  ('Nge-stalk medsos mantan tiap hari', 'red', 'kebiasaan'),
  ('Gak punya teman dekat', 'red', 'gaya_hidup'),
  ('Hubungan sama keluarga berantakan', 'red', 'gaya_hidup'),
  ('Boros banget, gak bisa nabung', 'red', 'gaya_hidup'),
  ('Gampang tersinggung soal kritik', 'red', 'kepribadian'),
  ('Suka bikin insecure pasangan', 'red', 'kepribadian'),
  ('Gak menghargai waktu orang lain', 'red', 'kebiasaan'),
  ('Sering PHP (Pemberi Harapan Palsu)', 'red', 'kebiasaan'),
  ('Gak punya ambisi atau tujuan hidup', 'red', 'gaya_hidup'),
  ('Doyan gosip dan ngejelek-jelekin orang', 'red', 'kepribadian'),
  ('Gak mau komitmen tapi minta eksklusif', 'red', 'kepribadian'),
  ('Kasar sama pelayan/ojol', 'red', 'kepribadian'),
  ('Sering moodnya berubah tiba-tiba', 'red', 'kepribadian'),
  ('Gak mau diperkenalkan ke teman', 'red', 'kebiasaan'),
  ('Hobi pinjam uang gak dibalikin', 'red', 'kebiasaan'),

  -- Green flags
  ('Selalu tepat waktu', 'green', 'kepribadian'),
  ('Mau dengerin ceritamu', 'green', 'kepribadian'),
  ('Inget hal-hal kecil tentang kamu', 'green', 'kepribadian'),
  ('Jujur dan transparan', 'green', 'kepribadian'),
  ('Minta maaf duluan kalau salah', 'green', 'kepribadian'),
  ('Punya teman-teman yang baik', 'green', 'gaya_hidup'),
  ('Hubungan sama keluarga sehat', 'green', 'gaya_hidup'),
  ('Punya tujuan hidup yang jelas', 'green', 'gaya_hidup'),
  ('Bisa kelola keuangan dengan baik', 'green', 'gaya_hidup'),
  ('Menghargai pendapatmu', 'green', 'kepribadian'),
  ('Supportif di saat susah', 'green', 'kepribadian'),
  ('Gak suka drama', 'green', 'kepribadian'),
  ('Baik sama semua orang', 'green', 'kepribadian'),
  ('Mau bertumbuh dan berubah', 'green', 'kepribadian'),
  ('Respek sama batas pribadimu', 'green', 'kepribadian'),
  ('Suka ngobrol tentang masa depan', 'green', 'kebiasaan'),
  ('Aktif tanya kabarmu', 'green', 'kebiasaan'),
  ('Konsisten antara kata dan perbuatan', 'green', 'kepribadian'),
  ('Punya hobi dan minat sendiri', 'green', 'gaya_hidup'),
  ('Gak ngatur-ngatur hidupmu', 'green', 'kepribadian'),
  ('Seneng ketemu keluargamu', 'green', 'kebiasaan'),
  ('Gak takut vulnerable sama kamu', 'green', 'kepribadian'),
  ('Dengerin tanpa langsung ngasih solusi', 'green', 'kepribadian'),
  ('Nge-hype pencapaianmu', 'green', 'kepribadian'),
  ('Tahu caranya bikin kamu ketawa', 'green', 'kepribadian'),
  ('Check-in saat kamu sibuk', 'green', 'kebiasaan'),
  ('Mau kompromi dan cari solusi bareng', 'green', 'kepribadian'),
  ('Gak ghosting, selalu kasih kabar', 'green', 'kebiasaan'),
  ('Bangga sama kamu di depan orang', 'green', 'kepribadian'),
  ('Ngehargain me-time kamu', 'green', 'kepribadian');
